on:
  push:
    branches:
      - master
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: master
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'sa-east-1'

      - name: Restore .NET dependencies
        run: |
          dotnet restore ./LambdaAttempt.sln

      - name: Build project
        run: |
          dotnet build ./LambdaAttempt.sln

      - name: Publish Shared
        run: |
          cd shared
          dotnet publish ./Shared.csproj

      - name: Synthesize CDK
        run: |
          cdk synth

      - name: Deploy CDK stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1'
        run: |
          cdk deploy --require-approval never
    